### ISSUE TITLE
Unable to install on Foundry 11.302

### ISSUE THREAD

**Issue by asacolips** [asacolips-projects/dungeonworld#126]
In GitLab by @jsavko on Jun 28, 2023, 18:16

```
FoundryVTT | 2023-06-28 16:13:18 | [info] FoundryVTT | Installed system dungeonworld
FoundryVTT | 2023-06-28 16:13:18 | [info] The file "lang/uk.json" included by system dungeonworld does not exist - 100%
FoundryVTT | 2023-06-28 16:13:18 | [error] The file "lang/uk.json" included by system dungeonworld does not exist
Error: The file "lang/uk.json" included by system dungeonworld does not exist
    at PackageAssetField.initialize (file:///D:/FoundryVTT-11.299/resources/app/dist/packages/package.mjs:1:1377)
    at SchemaField.initialize (file:///D:/FoundryVTT-11.299/resources/app/common/data/fields.mjs:517:23)
    at file:///D:/FoundryVTT-11.299/resources/app/common/data/fields.mjs:1009:40
    at Array.map (<anonymous>)
    at SetField.initialize (file:///D:/FoundryVTT-11.299/resources/app/common/data/fields.mjs:1009:18)
    at SetField.initialize (file:///D:/FoundryVTT-11.299/resources/app/common/data/fields.mjs:1089:26)
    at System._initialize (file:///D:/FoundryVTT-11.299/resources/app/common/abstract/data.mjs:216:27)
    at System._initialize (file:///D:/FoundryVTT-11.299/resources/app/dist/packages/package.mjs:1:3068)
    at System.updateSource (file:///D:/FoundryVTT-11.299/resources/app/common/abstract/data.mjs:415:33)
    at System._addInstalledPackageToCache (file:///D:/FoundryVTT-11.299/resources/app/dist/packages/package.mjs:1:9106)
```

Looks like the language file is missing which prevents install on FVTT 11.302

Edit: I checked the release zip and the uk.json does exist, so I'm not sure why it is reporting the file does not exist

**Comment by asacolips** [comment]
In GitLab by @Asacolips on Jun 29, 2023, 08:31

Thanks for reporting this @jsavko, I'll investigate this tonight :thumbsup:

**Comment by asacolips** [comment]
In GitLab by @Asacolips on Sep 21, 2023, 16:59

I'm unable to reproduce this issue with the version installed by the package manager. What may have happened is that if a zip version of this repository was downloaded, the language files (as well as other files, like CSS) aren't included and need to be compiled first. If so, that behavior is expected and is noted in the readme with the build instructions.
